title:              فواكة مجففة بالتبريد
description:         بديل السكاكر الصحي
author:             CandyStore
url:                "https://Bassel-Mohammed.github.io"
baseurl:            "/Fruit"  

# Social Profiles
twitter_username:   Aftyk_X
instagram_username:  Afytk_IG

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Products collection
collections:
  products:
    output: true
    permalink: /products/:title/
